### ISSUE TITLE
Class 'App\Http\Controllers\Search' not found

### ISSUE THREAD

**Issue by alihassan161820** [zizohassan/full-text-search-laravel#3]
(1/1) FatalThrowableError
Class 'App\Http\Controllers\Search' not found
i made all steps and it run in web.php but when i use it in controller it give me that error

**Comment by alihassan161820** [comment]
this is my code
              $products = Search::search(
                        "Product",
                        ['Name', 'Description','City'],
                        $product,
                        ['Name','Price','City','created_at'],
                        ['created_at','desc'],
                        true ,
                        30
                        );

**Comment by zizohassan** [comment]
AdvanceSearch\AdvanceSearchProvider\Facades\SearchFacades::search()
use like this
